production:
  adapter: mysql2
  database: mvms_prod
  host: localhost
  username: root
  password: nothing
  encoding: utf8

development:
  adapter: mysql2
  database: mvms_dev
  host: localhost
  username: root
  password: 
  encoding: utf8
  pool: 25


